name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  tag:
    name: Tag
    uses: ./.github/workflows/tag.yml
    secrets: inherit

  publish:
    name: Build & Publish
    needs:
      - tag
    uses: ./.github/workflows/publish.yml
    secrets: inherit
    with:
      image-name: ${{ needs.tag.outputs.image-name }}

  deploy:
    name: Deploy
    needs:
      - tag
      - publish
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    with:
      image-name: ${{ needs.tag.outputs.image-name }}
