on:
  workflow_call:
    inputs:
      image-name:
        description: 'Name of the image to deploy'
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy application
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} -p ${{ secrets.SSH_PORT }} << 'EOF'
            echo ${{ secrets.GHCR_PAT }} | docker login -u ${{ github.actor }} ghcr.io --password-stdin
          
            docker pull ${{ inputs.image-name }}
          
            docker logout ${{ env.REGISTRY }}
          EOF
