name: Publish

on:
  workflow_call:
    inputs:
      image-tag:
        description: 'Tag of the image to publish'
        required: true
        type: string

jobs:
  publish:
    name: Build & Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login
        run: |
          echo ${{ secrets.GHCR_PAT }} | docker login -u ${{ github.actor }} ${{ env.REGISTRY }} --password-stdin
      - name: Publish
        env:
          IMAGE_NAME: ${{ env.REGISTRY }}/likeajohny/portfolio:${{ inputs.image-tag }}
        run: |
          docker build . -f docker/Prod.Dockerfile -t ${{ env.IMAGE_NAME }}
          docker push ${{ env.IMAGE_NAME }}
