name: Publish Image

on:
  workflow_dispatch:
  push:

env:
  REGISTRY: ghcr.io

jobs:
  tag-image:
    name: Tag Image
    uses: ./.github/workflows/tag.yml
    secrets: inherit

  publish:
    name: Publish Image
    needs:
      - tag-image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login
        run: |
          echo ${{ secrets.GHCR_PAT }} | docker login -u ${{ github.actor }} ${{ env.REGISTRY }} --password-stdin
      - name: Publish
        env:
          IMAGE_NAME: ${{ env.REGISTRY }}/likeajohny/portfolio:${{ needs.tag-image.outputs.image-tag }}
        run: |
          docker build . -f docker/Prod.Dockerfile -t ${{ env.IMAGE_NAME }}
          docker push ${{ env.IMAGE_NAME }}
          
