on:
  workflow_call:
    inputs:
      image-name:
        description: 'Name of the image to publish'
        required: true
        type: string

jobs:
  publish:
    name: Build & Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login
        run: |
          echo ${{ secrets.GHCR_PAT }} | docker login -u ${{ github.actor }} ghcr.io --password-stdin
      - name: Publish
        run: |
          docker build . -f docker/Prod.Dockerfile -t ${{ inputs.image-name }}
          docker push ${{ inputs.image-name }}
