on:
  workflow_call:
    outputs:
      image-name:
        value: ${{ jobs.tag-image.outputs.image-name }}

jobs:
  tag-image:
    name: Tag Image
    runs-on: ubuntu-latest
    outputs:
      image-name: ${{ steps.get-image-name.outputs.result }}
    steps:
      - uses: actions/github-script@v7
        id: get-image-name
        with:
          result-encoding: string
          script: |
            const name = 'ghcr.io/likeajohny/portfolio';
            const tagPrefix = 'refs/tags/v';
            
            if (process.env.GITHUB_REF.startsWith(tagPrefix)) {
              return `${name}:process.env.GITHUB_REF.slice(tagPrefix.length)`;
            } else {
              return `${name}:latest`;
            }
